apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: servicea-1
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: servicea
        tbn_cluster: servicea
        stage: prod
        version: v1
    spec:
     initContainers:
      - args:
        - -p
        - "80"
        - -u
        - "999"
        - -m
        - REDIRECT
        - -i
        - '*'
        - -x
        - ""
        - -b
        - 8081,
        - -d
        - ""
        image: jimmysong/istio-release-proxy_init:1.0.0
        imagePullPolicy: IfNotPresent
        name: sm-init 
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
     restartPolicy: "Always"
     containers:
      - name: servicea
        image: vifoggy/servicea:lastest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP

      - name: envoy
        image: vifoggy/envoy-simple:latest
        imagePullPolicy: Always
        securityContext:
          privileged: false
          runAsUser: 999
        ports:
          - containerPort: 80
          - containerPort: 9999
        env:
        - name: ENVOY_XDS_HOST
          value: "rotor.default.svc.cluster.local" # Change if using a different namespace
        - name: ENVOY_XDS_PORT
          value: "50000"
        - name: ENVOY_NODE_ZONE
          value: default-zone
        - name: ENVOY_NODE_CLUSTER
          value: default-cluster
