apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: serviceb
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: serviceb
        tbn_cluster: serviceb
        stage: prod
        version: v1
    spec:
      restartPolicy: "Always"
      containers:
      - name: serviceb
        image: vifoggy/serviceb:lastest
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
          name: http
          protocol: TCP

      - name: envoy
        image: turbinelabs/envoy-simple:0.19.0
        imagePullPolicy: Always
        ports:
          - containerPort: 80
          - containerPort: 9999
        env:
        - name: ENVOY_XDS_HOST
          value: "rotor.default.svc.cluster.local" # Change if using a different namespace
        - name: ENVOY_XDS_PORT
          value: "50000"
        - name: ENVOY_NODE_ZONE
          value: default-zone
        - name: ENVOY_NODE_CLUSTER
          value: default-cluster
