apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: serviceb-1
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: serviceb
        tbn_cluster: serviceb
        stage: prod
        version: v1
    spec:
     initContainers:
      - args:
        - -p
        - "15001"
        - -u
        - "999"
        - -m
        - REDIRECT
        - -i
        - '*'
        - -x
        - ""
        - -b
        - 8082,
        - -d
        - ""
        image: vifoggy/sidecar-init:latest
        imagePullPolicy: IfNotPresent
        name: sm-init 
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
     restartPolicy: "Always"
     containers:
      - name: serviceb
        image: vifoggy/serviceb:lastest
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
          name: http
          protocol: TCP

      - name: envoy
        image: vifoggy/envoy-simple:lastest
        imagePullPolicy: Always
        securityContext:
          privileged: true
          runAsUser: 999
        ports:
          - containerPort: 15001
          - containerPort: 9999
        env:
        - name: ENVOY_XDS_HOST
          value: "rotor.default.svc.cluster.ci" # Change if using a different namespace
        - name: ENVOY_XDS_PORT
          value: "50000"
        - name: ENVOY_NODE_ZONE
          value: default-zone
        - name: ENVOY_NODE_CLUSTER
          value: default-cluster
