apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: servicec
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: servicec
    spec:
      containers:
      - name: servicec
        image: vifoggy/servicec:lastest
        ports:
        - containerPort: 8083
          name: svc-port
          protocol: TCP
      - name: envoy
        image: envoyproxy/envoy:latest
        ports:
          - containerPort: 9901
            protocol: TCP
            name: envoy-admin
          - containerPort: 15001
            protocol: TCP
            name: envoy-web
        volumeMounts:
          - name: envoy-config-volume
            mountPath: /etc/envoy-config/
        command: ["/usr/local/bin/envoy"]
        args: ["-c", "/etc/envoy-config/config.yaml", "--v2-config-only", "-l", "info","--service-cluster","servicec","--service-node","servicec", "--log-format", "[METADATA][%Y-%m-%d %T.%e][%t][%l][%n] %v"]
      volumes:
        - name: envoy-config-volume
          configMap:
            name: sidecar-config-c
            items:
              - key: envoy-config
                path: config.yaml
